version: '3.9'
services:
  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    restart: always
    ports:
      - "8280:80"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.nodejs
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - "37306:3306"
    volumes:
      - ./mysql/db_data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "8180:80"
      - "8444:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/src/app
volumes:
  angular_project:
